--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Muqsit/SkyWars
branches:
- master
projects:
  SkyWars:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.0
...
